### ISSUE TITLE
Update pedestrian route limit

### ISSUE THREAD

**Issue by KathleenLD** [valhalla/valhalla-docs#1]
https://github.com/valhalla/valhalla-docs/blob/gh-pages/api-reference.md#api-keys-and-service-limits

AFAIK, we've updated the pedestrian route limit to 250 km.

**Comment by kevinkreiser** [comment]
indeed: https://github.com/valhalla/chef-valhalla/blob/master/templates/default/valhalla.json.erb#L107

**Comment by kevinkreiser** [comment]
updated
