### ISSUE TITLE
Isochrones enpoint times out on transit

### ISSUE THREAD

**Issue by ustroetz** [valhalla/valhalla-docs#107]
When a sent a request to the isochrone endpoint with an invalid `costing` value I get a proper response:

```
$ curl -X GET "http://matrix.mapzen.com/isochrone?json=%7B%22locations%22:%5B%7B%22lat%22:40.744014,%22lon%22:-73.990508%7D%5D,%22costing%22:%22foo%22,%22contours%22:%5B%7B%22time%22:15%7D%5D%7D&api_key=mapzen-3zVshhL"
{"code":400,"status":"Bad Request","error":"No costing method found for 'foo'"}
```

However when use `transit` as `costing` it times out without returning anything.

```
$ curl -X GET "http://matrix.mapzen.com/isochrone?json=%7B%22locations%22:%5B%7B%22lat%22:40.744014,%22lon%22:-73.990508%7D%5D,%22costing%22:%22transit%22,%22contours%22:%5B%7B%22time%22:15%7D%5D%7D&api_key=mapzen-3zVshhL"
```

I assume the transit costing isn't fully implemented yet for isochrones, is it?

**Comment by dnesbitt61** [comment]
Thanks for the bug report. transit is not supported as a standalone costing option. It is meant as a costing part of a multimodal route, so you specify costing=multimodal. transit costing options can then be added into a multimodal request. We will look into making this more clear and fixing it so an error is returned.

**Comment by ustroetz** [comment]
Thanks @dnesbitt61 for the response. So do I understand this right, the following request will produce me a isochrone with the modes walking and transit?
```
{
	"locations": [{
		"lat": 40.744014,
		"lon": -73.990508
	}],
	"costing": "multimodal",
	"costing": "transit",
	"costing": "pedestrian",
	"contours": [{
		"time": 15
	}]
}
```

**Comment by dnesbitt61** [comment]
Just the multimodal costing (not including the transit and pedestrian).  The transit and pedestrian "costing options" are optional and allow the default options to be overridden. This works the same as the route options.

route?json={"locations":[{"lat":40.749706,"lon":-73.991562,"type":"break","street":"Penn Plaza"},{"lat":40.73093,"lon":-73.991379,"type":"break","street":"Wanamaker Place"}],"costing":"multimodal","costing_options":{"transit":{"use_bus":"1.0","use_rail":"0.0","use_transfers":"0.3"},"pedestrian":{"walking_speed":"4.1"}}}&api_key=mapzen-xxxxxxx

We are still tuning our isochrone service and its documentation so it is sort of an alpha service at this time. We hope to officially launch it soon.

**Comment by ustroetz** [comment]
Okay got it. Thanks for explaining and the great stuff you produce!

**Comment by rmglennon** [comment]
Looks like this has been resolved in the official release of isochrone service and in #108
