### ISSUE TITLE
Clarify language options in docs/lrm-mapzen

### ISSUE THREAD

**Issue by rmglennon** [valhalla/valhalla-docs#109]
This issue came in under the lrm-mapzen repo: https://github.com/mapzen/lrm-mapzen/issues/62

We should add a note to the tutorial and/or the lrm-mapzen readme about how to pass language options.

The language codes are documented here already: https://github.com/valhalla/valhalla-docs/blob/master/api-reference.md#directions-options

**Comment by kkowalsky** [comment]
added an example to the LRM-mapzen readme (https://github.com/mapzen/lrm-mapzen/pull/64)
