### ISSUE TITLE
Confusion around directory names

### ISSUE THREAD

**Issue by KathleenLD** [valhalla/valhalla-docs#12]
@rmglennon I don't know what your thoughts are on this, but what are your thoughts on just establishing directory names, rather than always reminding the user to use their own? I am finding that I'm getting confused about which directory I need to reference, and if I was able to set my own directories to all have the same name as yours, that would help. For example, lrm-valhalla is the directory that came w/ the lrm-valhalla download, but because it's such a general name, I'm not sure if sometimes that's how you're referring to your root directory for the whole tutorial. 

Let me know if this doesn't make sense, and we can discuss more.

**Comment by rmglennon** [comment]
Good comment. Let me see what makes sense to do. If I add a step telling you to rename leaflet-x-x-x version number to leaflet, then that would simplify the text that says to replace your own folder names when you add the reference to the path where the library resides on your machine. 

(Not sure if this affects the package manager crowd.)

**Comment by rmglennon** [comment]
I've added a step to rename the folders. This simplified the steps to reference the paths. Will link this issue to my pull request when it's ready to go.

![image](https://cloud.githubusercontent.com/assets/4380498/10034280/336853f2-6144-11e5-8411-222706864790.png)
