### ISSUE TITLE
Clean up API key and rate limit references in docs

### ISSUE THREAD

**Issue by rmglennon** [valhalla/valhalla-docs#126]
We've started a pattern to put the info on getting an API key and the Mapzen-hosted service limits in one topic in the documentation. Doing this is a start to separating the service from the open-source project (which we've been thinking about for ages). It also makes updates easier because there is only one place.

I did this with the new isochrone doc, but need to do it throughout the mobility help. 

https://mapzen.com/documentation/mobility/isochrone/api-reference/#inputs-of-the-isochrone-service

Need to remove content in mobility docs and replace with a link to the developer overview that has info for all Mapzen products.

**Comment by kkowalsky** [comment]
we should do this!
