### ISSUE TITLE
leaflet.routing.mapzen.css missing from unpkg.com

### ISSUE THREAD

**Issue by weatherpattern** [valhalla/valhalla-docs#154]
Currently, the tutorial references this css file: https://unpkg.com/lrm-mapzen@1.1.7/dist/
However,  leaflet.routing.mapzen.css is no longer in the https://unpkg.com/lrm-mapzen@1.1.7/dist/ directory.

Please add that file back to the folder.

**Comment by rmglennon** [comment]
Thanks for the feedback. The files were renamed, so you can find the current versions here:

https://unpkg.com/lrm-mapzen@1.1.7/dist/lrm-mapzen.js
https://unpkg.com/lrm-mapzen@1.1.7/dist/lrm-mapzen.css

I am working on some other updates that need to be made to this tutorial, including updating to Leaflet 1.0 and modifying the Tangram code.
