### ISSUE TITLE
Consider not self-closing CSS link tags in documentation

### ISSUE THREAD

**Issue by louh** [valhalla/valhalla-docs#16]
E.g.:
```
<link rel="stylesheet" href="leaflet.css"/>
```

This appears commonly, but is a relic of an ancient and bygone era of writing HTML. I have personally never been bitten by writing, instead, the semantically correct and much cleaner:

```
<link rel="stylesheet" href="leaflet.css">
```

I'm open to counter arguments.

**Comment by rmglennon** [comment]
I've updated the code to remove these (will reference this issue when it's on master). Thanks!
