### ISSUE TITLE
Crash when building tiles with recent Asia data

### ISSUE THREAD

**Issue by ianthetechie** [valhalla/valhalla-docs#176]
Hello, all.

When importing any of the last several OSM planet dumps (I've tried 3), `valhalla_build_tiles` crashes. In an attempt to at least get a server running on a reasonable subset of the world, I downloaded the latest extracts from Geofabrik to isolate the problem. It appears to be somewhere in Asia. After isolating the issue data-wise, I reran a fresh build with everything but Asia (and Antarctica; I didn't bother testing that) and everything worked. I didn't try to go much further than that, but if someone on the project thinks this would be helpful, I'm happy to do some more legwork.

<img width="566" alt="screen shot 2017-06-19 at 22 49 16" src="https://user-images.githubusercontent.com/2140440/27314388-91b20a50-5541-11e7-89d0-64786c04cd44.png">

**Comment by ianthetechie** [comment]
Oh, and I suppose it'd be helpful if I mentioned what version I'm using ;) I'm using the PPA package on Ubuntu 16.04.2

**Comment by gknisely** [comment]
Hi @ianthetechie 
This issue was due to bad data entered by users in restrictions.  The fix has already been checked into master; however, we have not created a new PPA version yet.  I believe we plan to release a new version tomorrow.  We will let you know when it is available.  

--Greg.

**Comment by gknisely** [comment]
New PPA was released.  Can you try it out?

**Comment by ianthetechie** [comment]
Fantastic. Kicking off an Asia build right now to test.

**Comment by ianthetechie** [comment]
All appears well. Thanks for the quick fix!

**Comment by gknisely** [comment]
:+1:
