### ISSUE TITLE
Roundabout Inconsistencies

### ISSUE THREAD

**Issue by farough** [valhalla/valhalla-docs#190]
Hi, 

I'm hoping this is the correct place to create this issue. 

I've started to implement Mapzen into our mobile apps, but I'm having issues with the directions regarding Roundabouts. We're using biking directions and I'm finding many of the roundabouts give inconsistent and often inaccurate values for the exit number. Even going to a single roundabout and making a request for each different exit, I often get the same exit number in both the exit count and the description to the user in which exit to take. 

This roundabout in particular:
https://www.google.ca/maps/place/49%C2%B004'39.9%22N+6%C2%B006'04.7%22E/@49.077756,6.0999106,17z/data=!3m1!4b1!4m6!3m5!1s0x0:0x0!7e2!8m2!3d49.0777564!4d6.1013132

Coming from the North East, the exit number says to take the first exit for the first 3 exits and the 4th and 5th exit say take the 2nd exit. 

Thanks, let me know if I should post this issue in another place.

**Comment by dgearhart** [comment]
@farough Could you please close this issue and open an issue here:
https://github.com/valhalla/valhalla/issues
Thank you for reporting

**Comment by farough** [comment]
Alright, done. Thank you.
