### ISSUE TITLE
Which are all the maneuver 'type' strings?

### ISSUE THREAD

**Issue by costales** [valhalla/valhalla-docs#25]
Hi!

I'd like to localize my project.

Where could I read all the possible strings for the types here https://github.com/valhalla/valhalla-docs/blob/master/api-reference.md

By example, for this instruction:
`Bear left onto Gijon El Llano`
Would be `Bear left onto`.

Thanks in advance!

**Comment by kevinkreiser** [comment]
hi @costales we havent yet began the process of localizing our narrative generation code. so as it currently stands most of these strings are directly in the [code](https://github.com/valhalla/odin/blob/master/src/odin/narrativebuilder.cc) within the `odin` progject. @dgearhart can elaborate on that if you need.

however we do plan to do localization on the server side. we should have a mechanism in place where, in true open source fashion, people like yourself could give us the proper strings and we could serve them up when you set `language=es_ES` in your request, for example

**Comment by dgearhart** [comment]
We are starting to discuss the I18N of our narrative strings - we are hoping to provide language specific files that users could easily create and modify. If you have any suggestion we would be happy to hear.

**Comment by costales** [comment]
Thanks a lot for your answers :)

IMHO it would be good (too) a public/know method to descompose a English phrase. It's a bit complicate now because of the use of several streets, signs, joins of phrases/streets... And this could be a door to localize from the client side, because I could use a language that you'll not set in the server as language=ast_ES ;)

A big hug!

**Comment by kevinkreiser** [comment]
we are considering a formatting of the text output such that the pieces you mentioned would be easily identifiable, for example something like:

    turn <span type="turn">left</span> on <span type="street_name">Gijon El Llano</span>

in the end though, we want to make it so that you can make a pull request to us with the `ast_ES` strings in it so that other people that want Asturian can also get it!

**Comment by dgearhart** [comment]
yes @costales we would like have an open system that will enable you and others to contribute specific languages. So if we would supply a file with narrative phrases then users could translate the static phrases and reorder the static and dynamic parts as needed - for the "Bear left" example:

en_US file:
phrase#0: "Bear left"
phrase#1: "Bear left onto <STREET_NAMES>"

es_ES file:
phrase#0: "Gire a la izquierda"
phrase#1: "Gire a la izquierda en <STREET_NAMES>"

you could supply the ast_ES version

**Comment by costales** [comment]
Yes, for my project I'm using launchpad.

I was thinking in this, and I think that a user can compose the phrase from
the JSON. I'll try this: http://paste.ubuntu.com/12637812/ Becaue your
composed phrase is a bit to create from the JSON, but I think your phrase
is perfect, really useful.

If you open the translations (and the API) for any language it would be
enough and perfect.

Thanks a lot!

PS: Is there any date about this?

**Comment by lionel-bijaoui** [comment]
How can I help with translation (French) ?

**Comment by kevinkreiser** [comment]
@lionel-bijaoui thanks for asking! we aren't quite ready yet but we'll notify you and @costales when we have documentation/instructions in place for contributing translations! we would really appreciate any help we can get!

**Comment by dgearhart** [comment]
@costales you can now contribute an Asturian/Spain narrative language file.
If you are able, here are the instructions:
https://github.com/valhalla/odin/blob/master/locales/README.md

The file name for the Asturian/Spain narrative language should be:
ast-ES.json
 
The posix_locale value should be:
es_ES.utf8

**Comment by dgearhart** [comment]
@lionel-bijaoui you can now contribute an French/France narrative language file.
If you are able, here are the instructions:
https://github.com/valhalla/odin/blob/master/locales/README.md

The file name for the  French/France narrative language should be:
fr-FR.json

The posix_locale value should be:
fr_FR.utf8

**Comment by costales** [comment]
I'll do it :) Thanks a lot for your API!!

-- 
Sent using Dekko from my Ubuntu device

**Comment by dgearhart** [comment]
thank you @costales

**Comment by costales** [comment]
@dgearhart It's a big work. Are necessary the "example_phrases" or are just an example for translators?

**Comment by dgearhart** [comment]
@costales the  "example_phrases" are not required to be translated - they are for communication aids for translator and developer

**Comment by dgearhart** [comment]
@costales I was wondering if you had time to work on the Asturian/Spain narrative language file? If so, how is it going? Any issues?

**Comment by dgearhart** [comment]
@lionel-bijaoui  I was wondering if you had time to work on the French narrative language file? If so, how is it going? Any issues?

**Comment by costales** [comment]
@dgearhart So much work in these days, sorry.
Anyway I think is so much phrases :P I'll work on it ;)

**Comment by rmglennon** [comment]
I think this can be closed now. The instructions for localization are here now, including ES and FR options: https://github.com/valhalla/valhalla/tree/master/locales
