### ISSUE TITLE
How to avoid Tolls?

### ISSUE THREAD

**Issue by costales** [valhalla/valhalla-docs#27]
Hi!

From the documentation:
https://github.com/valhalla/valhalla-docs/blob/master/api-reference.md
It's not so clear for me how to avoid all the tolls.

Should be like this? `"costing_options":{"auto":{"toll_booth_penalty":100000.0}}`

`https://valhalla.mapzen.com/route?json={"locations":[{"lat":42.358528,"lon":-83.271400},{"lat":42.996613,"lon":-78.749855}],"costing":"auto","costing_options":{"auto":{"toll_booth_penalty":100000.0}}}&api_key=valhalla-xxxxxx`

Thanks in advance!

**Comment by dnesbitt61** [comment]
that should do it as long as there is a tolll booth in OSM (on a node).

**Comment by costales** [comment]
@dnesbitt61 I asked because It's not working in this route. Is an OSM issue then?

`https://valhalla.mapzen.com/route?json={%22locations%22:[{%22lat%22:43.515955,%22lon%22:-5.655354999999999},{%22lat%22:40.4167047,%22lon%22:-3.7035825}],%22costing%22:%22auto%22}&api_key=valhalla-xxxxxxx`

`https://valhalla.mapzen.com/route?json={%22locations%22:[{%22lat%22:43.515955,%22lon%22:-5.655354999999999},{%22lat%22:40.4167047,%22lon%22:-3.7035825}],%22costing%22:%22auto%22,%22costing_options%22:{%22auto%22:{%22toll_booth_penalty%22:100000.0}}}&api_key=valhalla-xxxxxxx`

In the last you can see a `"toll":true` in the AP-66.

Thanks in advance!

**Comment by gknisely** [comment]
@costales can you send us the OSM.org link to the node or way that has
toll=true.  Thanks.  Greg.

**Comment by costales** [comment]
@gknisely 

It's this mapzen response:
{"begin_shape_index":702,"street_names":["AP-66","Autopista Ruta de la Plata"],"time":1583,"type":8,"end_shape_index":1457,"instruction":"Continue on AP-66\/Autopista Ruta de la Plata.","length":47.760,"verbal_transition_alert_instruction":"Continue on AP-66.","toll":true,"verbal_pre_transition_instruction":"Continue on AP-66, Autopista Ruta de la Plata for 47.8 kilometers."}

And this OSM way:
http://www.openstreetmap.org/way/4830329

As you can see, toll is set.

Thanks in advance!

**Comment by dnesbitt61** [comment]
It looks like we need to apply penalties to ways marked as tolls in addition to nodes marked as tolls. We will look into this further and let you know what we find.

**Comment by costales** [comment]
Thanks a lot :)

**Comment by dnesbitt61** [comment]
I believe this is fixed in production. Let us know if you still see issues.

**Comment by costales** [comment]
It works :) Thanks a lot!
One question more please, in this parameter:
"toll_booth_penalty":100000.0
Which number should I use?

**Comment by kevinkreiser** [comment]
@costales that number is in seconds. its basically telling the routing engine that you will sit at that tollbooth for that many seconds

**Comment by costales** [comment]
@kevinkreiser Oh! Great ;)
Thanks a lot! I'm impressed with your support and good work!
A big hug
