### ISSUE TITLE
Tutorial - plugin-organization link doesn't really apply

### ISSUE THREAD

**Issue by louh** [valhalla/valhalla-docs#34]
In https://github.com/valhalla/valhalla-docs/blob/master/add-routing-to-a-map.md, there is this text:

> Note that there are guidelines for organizing code for Leaflet plug-ins. You can use a more sophisticated structure for your own work as you progress in your development.

The link that it points to (https://github.com/Leaflet/Leaflet/blob/master/PLUGIN-GUIDE.md) is for people who are going to be project owners of their own Leaflet plugin that is intended to be distributed to a wider audience of developers. It doesn't apply to people who are creating personal projects that use Leaflet. This is going to be _extremely_ confusing for people in the latter group who aren't aware of the difference.

**Comment by rmglennon** [comment]
Should we remove that sentence then?

**Comment by louh** [comment]
Yeah, I think so. I was thinking of other ways to lead into "You can use a more sophisticated structure for your own work as you progress in your development," but if the intent is to ease-in beginner devs, it's really just extraneous information at this point.

**Comment by rmglennon** [comment]
Deleted that line as part of some other updates this week. (finally)
