### ISSUE TITLE
Tutorial - "Unhandled promise rejection Cannot assign to read only property 'layer_name' of false"

### ISSUE THREAD

**Issue by michaellehmkuhl** [valhalla/valhalla-docs#45]
Hello.

I'm working through the tutorial https://mapzen.com/documentation/turn-by-turn/add-routing-to-a-map/, and ran into a problem getting the initial Tangram layer added to the map.

Here's a screenshot of the error I'm seeing in the console (using https://mapzen.com/tangram/tangram.debug.js for more clarity):
http://ep.d.pr/19TMS/2Z5DQiAB

HTML and scripts
```
<body>
  <div id="map"></div>
  <script src="leaflet/leaflet.js"></script>
  <script src="https://mapzen.com/tangram/tangram.debug.js"></script>
  <script src="leaflet-routing-machine/leaflet-routing-machine.js"></script>
  <script src="lrm-valhalla/lrm-valhalla.js"></script>
  <script>
    var map = L.map('map');
    var layer = Tangram.leafletLayer({
      scene: 'https://raw.githubusercontent.com/valhalla/valhalla-docs/master/examples/skin-and-bones-scene.yaml',
      attribution: '<a href="https://mapzen.com/tangram" target="_blank">Tangram</a> | <a href="http://www.openstreetmap.org/about" target="_blank">&copy; OSM contributors | <a href="https://mapzen.com/" target="_blank">Mapzen</a>',
    });
    layer.addTo(map);
    map.setView([41.8758,-87.6189], 16)
  </script>
</body>
```

Any help you can provide would be great. I'm excited to start working with Valhalla.

Thanks.

Michael

**Comment by michaellehmkuhl** [comment]
I was able to determine that the issue lies in somewhere in the skin-and-bones-scene.yaml scene file. I experimented with using the https://github.com/tangrams/simple-demo/blob/gh-pages/scene.yaml file instead, which worked for me. I haven't been able to narrow down specifically what piece of the skin-and-bones-scene.yaml file is problematic.

**Comment by rmglennon** [comment]
Thanks for reporting this. Glad you got it working with that other scene!

Mapzen released a few new map styles since this tutorial was written, so I'll update the tutorial to use one of them instead. The Cinnabar style most closely resembles the skin-and-bones style.

https://raw.githubusercontent.com/tangrams/cinnabar-style/gh-pages/cinnabar-style.yaml

**Comment by bcamper** [comment]
Thanks, sorry for the trouble @michaellehmkuhl.

@rmglennon & @nvkelso: as we have been frequently updating Skin & Bones to track new Tangram features, it's likely a syntax incompatibility between 0.3 and 0.4. @rmglennon, let's update this tutorial (and others / as a general policy) to point to specific Tangram and scene file versions (@nvkelso, reminder we should add release/version numbers for styles too), e.g. to load current Tangram 0.4.x:

`<script src="https://mapzen.com/tangram/0.4/tangram.min.js"></script>`

**Comment by rmglennon** [comment]
I've updated the tutorial on https://mapzen.com/documentation/turn-by-turn/add-routing-to-a-map/. It should all be working again!

Among the other changes, the map uses the Cinnabar style and specifies a Tangram version.

Thanks @michaellehmkuhl for letting us know about this!
