### ISSUE TITLE
Use and document a CDN for Leaflet Routing Machine

### ISSUE THREAD

**Issue by migurski** [valhalla/valhalla-docs#49]
We are getting “good idea” feedback from @perliedman about a CDN for LRM (https://github.com/perliedman/leaflet-routing-machine/issues/192), let’s help that along. CDNJS might be confusing and weird, but in principle any stable URL on S3 or behind Fastly should work. @baldur might have some opinions on this.

* Raw markdown source: https://github.com/valhalla/valhalla-docs/blob/master/add-routing-to-a-map.md#download-and-install-the-dependencies
* Public view: https://mapzen.com/documentation/turn-by-turn/add-routing-to-a-map/

**Comment by baldur** [comment]
My thoughts are if we can get away with creating a bucket and then deliver the content as:

bucket_name.s3-website-us-east-1.amazonaws.com/{filename}.js

Then that would be the least amount of effort

**Comment by migurski** [comment]
Could it have a nice CNAME?

**Comment by baldur** [comment]
that would require a ssl certificate ... would putting it under mapzen.com/somepath which then proxies to s3 work?

We do that already for tangram and I think it's being used ... @bcamper can speak to it better.

**Comment by migurski** [comment]
…oh yeah, that’d be perfect. Under `/common/libs` perhaps?

**Comment by baldur** [comment]
works for me

**Comment by migurski** [comment]
Can you help show me what needs to happen to make that real?

**Comment by baldur** [comment]
absolutely in essentially it's just a matter of adding a build step in
circleci which then publishes to the s3 bucket already mapped. @migurski
lets set something up where we can go over this.

On Wed, Jan 13, 2016 at 2:00 AM, migurski <notifications@github.com> wrote:

> Can you help show me what needs to happen to make that real?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/valhalla/valhalla-docs/issues/49#issuecomment-171197209>
> .
>



-- 
Baldur Gudbjornsson
VP Engineering
Mapzen - 347 268 1815

**Comment by perliedman** [comment]
Don't know if this solves this issue for you, but LRM is now available from CDNJS: https://cdnjs.com/libraries/leaflet-routing-machine

**Comment by migurski** [comment]
That’s great, Per, thanks for letting us know

**Comment by rmglennon** [comment]
Tutorial instructions updated to use website versions of Leaflet, LRM, and LRM-Mapzen (which is available through npm, but that also acts as a CDN with a URL, like https://npmcdn.com/lrm-mapzen/dist/lrm-mapzen.js.). This greatly simplified the tutorial set up instructions because we don't need to tell users to download any of these files now.
