### ISSUE TITLE
Update some OSM wikis for Valhalla/Turn-by-Turn

### ISSUE THREAD

**Issue by rmglennon** [valhalla/valhalla-docs#57]
There are a few OSM wikis that should be updated to include Valhalla/Turn-by-Turn.

- [x] http://wiki.openstreetmap.org/wiki/Routing/online_routers (placeholder table column)
- [x] http://wiki.openstreetmap.org/wiki/Valhalla (there's a start to this page)
- [x] http://wiki.openstreetmap.org/wiki/Routing (under End Users Routing Software)

Putting this into an issue so it doesn't get forgotten in email - cc @burritojustice @dnesbitt61 @gknisely @kdiluca

**Comment by dnesbitt61** [comment]
Filled in much of the column - should revisit.

**Comment by rmglennon** [comment]
Pretty sure these are all done now. Thanks @gknisely
