### ISSUE TITLE
Behaviour not consistent when trying to avoid tolls

### ISSUE THREAD

**Issue by eliboni** [valhalla/valhalla-docs#71]
I'm experiencing an inconsistent behaviour when trying to avoid tolls roads:

Example1: The below 2-legs trip returned shape avoids toll roads as I would expect:
http://valhalla.mapzen.com/route?api_key=valhalla-xxx&json={"locations":[{"lat": 45.113120,"lon": 11.776360},{"lat": 45.020066,"lon": 11.706396},{"lat":44.86595,"lon": 11.575852}],"costing":"auto","costing_options":{"auto":{"toll_booth_penalty":10000.0}},"directions_options": { "unit":"km", "narrative":"false" }}

Example2: However the below 1-legs (obtained by removing the 2nd location) does NOT avoid tolls (it uses part of A13 highway):
http://valhalla.mapzen.com/route?api_key=valhalla-xxx&json={"locations":[{"lat": 45.113120,"lon": 11.776360},{"lat":44.86595,"lon": 11.575852}],"costing":"auto","costing_options":{"auto":{"toll_booth_penalty":10000.0}},"directions_options": { "unit":"km", "narrative":"false" }}

what is surprising is that the removed location is contained in the shape returned by Example2,  so I would have expected the same behaviour.

Note, toll_booth is there:https://www.openstreetmap.org/node/255852706
as well as the way https://www.openstreetmap.org/way/28910847 has toll=yes so the returned shape in Example2 should have not entered into the toll road in any case.

What am I doing wrong? Thanks in advance (note: this might linked to #27)

Enrico

**Comment by dnesbitt61** [comment]
Thanks for reporting this issue. I think this is an issue with our logic that creates shortcut edges. I am testing a fix to our data import logic and will let you know if that is the case. I don't think you are doing anything wrong!

**Comment by eliboni** [comment]
Thanks a lot! Let me know if you need more details or additional examples since I could replicate the same on other trips

**Comment by dnesbitt61** [comment]
This issue should be fixed in production now. If you find other examples of avoid toll issues please let us know, but hopefully this issue is fixed. Thanks for your help!

**Comment by eliboni** [comment]
just exceptional!!!
