### ISSUE TITLE
question on location limits

### ISSUE THREAD

**Issue by tomay** [valhalla/valhalla-docs#95]
Hello, thank you for this great service. I have a question about limits.

The docs [here](https://mapzen.com/documentation/turn-by-turn/api-reference/) say both that "Pedestrian routes have a limit of 50 locations and 250 kilometers.", and later, under "Locations" that "Locations are visited in the order specified, with a maximum of eight locations currently supported."

In testing, I was able to pass many more than 8 locations. Can you clarify what limits are in effect here?

**Comment by kdiluca** [comment]
@tomay, thanks for bringing this to our attention.  The limits stated in the "API keys and service limits" are the correct documentation to follow.  I have fixed the "Locations" section of the documentation and it should be updated in production shortly.

**Comment by tomay** [comment]
great - thank you very much
