### ISSUE TITLE
How to setup route server with some osm extract?

### ISSUE THREAD

**Issue by karme** [valhalla/valhalla-docs#96]
maybe I missed it, but I couldn't find a tutorial describing how to use all the tools to setup a route server?

**Comment by kevinkreiser** [comment]
yeah we are in a bit of flux right now. but if you want to run one yourself and make your own routing graph tiles yourself you can do that by following this little blurb: https://github.com/valhalla/tools#building-and-running-valhalla

**Comment by kevinkreiser** [comment]
we also have docker if you are interested in that sort of thing: https://github.com/valhalla/valhalla-docker

**Comment by karme** [comment]
Kevin Kreiser <notifications@github.com> writes:

> yeah we are in a bit of flux right now. but if you want to run one
> yourself and make your own routing graph tiles yourself you can do
> that by following this little blurb:
> https://github.com/valhalla/tools#building-and-running-valhalla

somehow missed that one. Got my first routing request answered :-)
Thanks!

**Comment by kevinkreiser** [comment]
no problem thank you!
